### PR TITLE
[#1887] switch to 15 fork of angularjs nvd3 directives dependency

### PR DESCRIPTION
**Pull request by vsharma2013**
Added Tooltip content value formatter for pie charts.

### CODE REVIEW

**Comment by vsharma2013** [comment]
@ppuleo FYI

**Comment by ppuleo** [comment]
@vsharma2013 I think you meant to submit this PR to the X15 fork of this project?

**Comment by vsharma2013** [comment]
@ppuleo yes thats correct.

**Comment by ppuleo** [comment]
@vsharma2013 ok, then please close this PR and reopen against https://github.com/x15software/angularjs-nvd3-directives

**Pull request closed without merging**
