### PR TITLE
Migrating to nvd3-community

### PR DESCRIPTION
**Pull request by LostInBrittany**
Sadly the original developer of nvd3 has long since moved on to other things, and the last maintainer said he does not have time anymore.  But a recent fork, [nvd3-community](https://github.com/nvd3-community/nvd3) has continued the project, and  they are releasing new versions that add functionalities and correct bugs. 

I propose here to migrate  angularjs-nvd3-directives to this new project.

### CODE REVIEW

**Comment by portante** [comment]
Hi @LostInBrittany, your changes here would make cmaurer's repository have code that references your repository.  Not sure that is what we want, is it?

I think instead, you might want to post a PR with a change to the README.md file which tells folks this library is no longer maintained and to use yours instead.

What do you think?

And how committed are you to maintaining your fork?

**Comment by Resseguie** [comment]
Is it just the bower.json file with those references? Why not scrap that and cherry-pick the other commits? 

(No comments either way on the other updates, I've not gone through it yet.)

Or do we just need an nvd3-community fork of the directive code since it looks like this repo isn't being maintained either? See #314 and #307 

I'd love to see @liquidpele include an updated directive repo under the new nvd3-community org.

**Comment by portante** [comment]
Just an update, before we take in any further pull requests, we are going to put in place some unit tests to help us maintain stability.  Until that time, pull requests will be waiting.

**Comment by portante** [comment]
Can you resubmit this now that we have fixed the getD3Selector problem, with unit tests?  I don't think we need to make changes to work with nvd3-community now.

**Comment by greg0x** [comment]
Hey guys

I am not sure what's happening around nvd3 but wanted to give you a quick heads up:
the last commit for nvd3-community was more than a month ago, it was merged back to the nvd3 and now @robinfhu is working on the lib

**Comment by portante** [comment]
@minutuslausus, thanks we are working with Novus and @liquidpele on as well.

**Pull request closed without merging**
